version: '3.8'

services:
  catalog-api:
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=host.docker.internal;Port=5435;Database=postgres;Username=omsadmin;Password=123qwe
      - RabbitMQ__Host=host.docker.internal
      - RabbitMQ__Port=5672
      - RabbitMQ__User=omsadmin
      - RabbitMQ__Pass=123qwe

  procurement-api:
    build:
      context: .
      dockerfile: Procurement.Api/Dockerfile
    ports:
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=host.docker.internal;Port=5435;Database=postgres;Username=omsadmin;Password=123qwe
      - RabbitMQ__Host=host.docker.internal
      - RabbitMQ__Port=5672
      - RabbitMQ__User=omsadmin
      - RabbitMQ__Pass=123qwe

  gateway-api:
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    ports:
      - "5000:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Add any gateway-specific env vars here