services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: omsadmin
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: postgres
    ports: ["5435:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["8081:80"]

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: omsadmin
      RABBITMQ_DEFAULT_PASS: 123qwe
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  rabbitmq-data:
